version: "3.9"

services:

  caddy:
    image: "docker.io/hectorm/caddy:latest"
    restart: "on-failure:3"
    ports:
      - "8080:8080/tcp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "www-alice:/var/www/data/alice/:ro"
      - "www-bob:/var/www/data/bob/:ro"
      - "www-dan:/var/www/data/dan/:ro"

  dropbear:
    image: "docker.io/hectorm/dropbear:latest"
    restart: "on-failure:3"
    ports:
      - "2222:2222/tcp"
    environment:
      # USERNAME:(plain|encrypted):PASSWORD:UID:GID
      DROPBEAR_USERS: |
        alice:::1000:1000
        bob:plain:password:1001:1001
        dan:encrypted:$$5$$salt$$Gcm6FsVtF/Qa77ZKD.iwsJlCVPY0XSMgLJL0Hnww/c1:1002:1002
    volumes:
      - "./keys/alice_ed25519.pub:/home/alice/.ssh/authorized_keys.d/alice_ed25519.pub:ro"
      - "dropbear-keys:/etc/dropbear/"
      - "www-alice:/home/alice/data/"
      - "www-bob:/home/bob/data/"
      - "www-dan:/home/dan/data/"

volumes:

  dropbear-keys:
  www-alice:
  www-bob:
  www-dan:
